baseurl = "/"

languageCode = "en-us"
title = "Harry Cresswell"
canonifyURLs = true
metaDataFormat = "toml"
buildDrafts = false

[author]
    name = "Harry Cresswell"
    email = "harry@harrycresswell.com"


# color-codes for highlighting derived from this style
#pygmentsStyle = "monokai"
#pygmentsuseclasses = true

# Because why the hell not
enableEmoji = true

# Enable Disqus by removing comments
#disqusShortname = "harrycresswell"

# Enable analytics
googleAnalytics = "UA-84736644-1"

[permalinks]
    articles = "/:section/:slug/"
    reading = "/:section/:slug/"
    page = "/:title/"

[[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 0
[[menu.main]]
    name = "Mood"
    url = "https://thevastnothingnessofspace.tumblr.com/"
    weight = 5
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
[[menu.main]]
    name = "Newsletter"
    url = "/newsletter/"
    weight = 15

[params]
  Keywords = "UX Design, UI Design, Front-end Development, Small businesses, Automation"
  Description = "Design. Typography. London. Hamburg."
  Location = "London, UK"
  Email = "harry@harrycresswell.com"

[indexes]
  tag = "tags"
  topic = "topics"
  series = "series"
