baseurl = "https://dancer-development-38716.netlify.com/"

languageCode = "en-us"
defaultContentLanguage = "en"
title = "Harry Cresswell"
canonifyURLs = true
metaDataFormat = "toml"
buildDrafts = false

# color-codes for highlighting derived from this style
pygmentsStyle = "monokai"
pygmentsuseclasses = true

enableEmoji = true
# Enable comments by entering your Disqus shortname
# disqusShortname = "Your Disqus shortname"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-84736644-1"

[permalinks]
    articles = "/:section/:title/"
    reading = "/:section/:title/"
    page = "/:title/"

[[menu.footer]]
    name = "Articles"
    url = "/articles/"
    weight = 0
[[menu.footer]]
    name = "Reading List"
    url = "/reading/"
    weight = 5
[[menu.footer]]
    name = "About"
    url = "/about/"
    weight = 10
[[menu.footer]]
    name = "Github"
    url = "https://github.com/harrycresswell/"
    weight = 15

[params]
  Keywords = "keywords go in here"
  Description = "Helping small businesses grow — using design, code and photography."
  Location = "London, UK"
  Email = "studio@harrycresswell.com"
  GithubID = "Your Github ID"
  TwitterID = "Your Twitter ID"

[indexes]
  tag = "tags"
  topic = "topics"
  series = "series"
