baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "My New Hugo Site"

MetaDataFormat = ""
theme = ""

# Enable comments by entering your Disqus shortname
disqusShortname = "Your Disqus shortname"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "Your Google Analytics tracking code"

[permalinks]
    articles = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = ""
[[menu.main]]
    name = "Twitter"
    url = ""


[params]
  Keywords = "keywords go in here"
  Description = "Honest actionable advice for creatives and independent business owners."

  Avater = "img/avatar.jpg"
  Email = "you@example.com"

  GithubID = "Your Github ID"
  TwitterID = "Your Twitter ID"
