baseurl = "/"
languageCode = "en-us"
title = "My New Hugo Site"

MetaDataFormat = ""
theme = ""

# Enable comments by entering your Disqus shortname
disqusShortname = "Your Disqus shortname"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-84736644-1"

[permalinks]
    articles = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Hire me"
    url = "/design-consulting/"
[[menu.main]]
    name = "Articles"
    url = "/articles/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/harrycresswell"

[params]
  Keywords = "keywords go in here"
  Description = "Honest actionable advice for creatives and independent business owners."
  Location = "London, UK"
  Avater = "img/avatar.jpg"
  Email = "you@example.com"
  GithubID = "Your Github ID"
  TwitterID = "Your Twitter ID"

[taxonomies]
  tag = "tags"
  category = "categories"
