baseurl = "https://dancer-development-38716.netlify.com/"

languageCode = "en-us"
title = "Harry Cresswell"
canonifyURLs = true
metaDataFormat = "toml"
buildDrafts = false

# color-codes for highlighting derived from this style
#pygmentsStyle = "monokai"
#pygmentsuseclasses = true

# Because why the hell not
enableEmoji = true

# Enable Disqus by removing comments
#disqusShortname = "harrycresswell"

# Enable analytics
googleAnalytics = "UA-84736644-1"

[permalinks]
    articles = "/:section/:title/"
    reading = "/:section/:title/"
    page = "/:title/"

[[menu.footer]]
    name = "Articles"
    url = "/articles/"
    weight = 0
[[menu.footer]]
    name = "Reading List"
    url = "/reading/"
    weight = 5
[[menu.footer]]
    name = "About"
    url = "/about/"
    weight = 10
[[menu.footer]]
    name = "Github"
    url = "https://github.com/harrycresswell/"
    weight = 15

[params]
  Keywords = "UX Design, UI Design, Front-end Development, Small businesses, Automation"
  Description = "Helping small businesses grow — using design, code and photography."
  Location = "London, UK"
  Email = "studio@harrycresswell.com"

[indexes]
  tag = "tags"
  topic = "topics"
  series = "series"
