baseurl = "/"
languageCode = "en-us"
title = "Harry Cresswell"

MetaDataFormat = ""
theme = ""

pygmentsuseclasses = false

# Enable comments by entering your Disqus shortname
disqusShortname = "Your Disqus shortname"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-84736644-1"

[permalinks]
    articles = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 0
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 5
[[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 10
[[menu.main]]
    name = "Reading List"
    url = "/reading-list/"
    weight = 15

[[menu.footer]]
    name = "Articles"
    url = "/articles/"
[[menu.footer]]
    name = "Github"
    url = "https://github.com/harrycresswell/"
[[menu.footer]]
    name = "About"
    url = "/about/"

[params]
  Keywords = "keywords go in here"
  Description = "I help small businesses grow – using design, code and a good bit of content marketing know-how."
  Location = "London, UK"
  Email = "studio@harrycresswell.com"
  GithubID = "Your Github ID"
  TwitterID = "Your Twitter ID"

[taxonomies]
  tag = "tags"
  category = "categories"
